### ISSUE TITLE
can you add anothersome features for priorityqueue?

### ISSUE THREAD

**Issue by Nyx2022** [idsulik/go-collections#5]
sorry,I forget some important features in  [#3](https://github.com/idsulik/go-collections/issues/3)，

1. it's Clone()  to return a copy version of current PriorityQueue
2. It.s detect current pq *PriorityQueue[T] if is nil in UnmarshalJSON,if it is , init it first
3. ContainsBy(func) which can check if in queue by self defined func to check just some attr in element

thank you in advance!

**Comment by idsulik** [comment]
@Nyx2022 implemented the first and the third features, the second one couldn't be implemented, there is no way to initialize the struct inside a method
