### ISSUE TITLE
can you add another some features for priorityqueue?

### ISSUE THREAD

**Issue by Nyx2022** [idsulik/go-collections#7]
1. RemoveFunc to remove some element by func, 
2. GetFunc to get one element by func, 
3. LenFunc() to get length for match func.

i also wanna know about if the PriorityQueue and it's funcs are goroutine safety ?
thank you in advance

**Comment by idsulik** [comment]
Hi @Nyx2022 

Implemented the methods.  

> i also wanna know about if the PriorityQueue and it's funcs are goroutine safety ?  

No, they're not goroutine safe. I have a plan to create thread-safe version of the structures
